In [ ]:
import os
import sys

sys.stderr = open(os.devnull, "w")

import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import psycopg2
import pytz
from datetime import timedelta
from dateutil.relativedelta import relativedelta
from sktime.forecasting.tbats import TBATS
from sklearn.metrics import mean_absolute_error, root_mean_squared_error

warnings.filterwarnings('ignore', category=FutureWarning)

/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/tbats/abstract/ParamsOptimizer.py:150: RuntimeWarning: divide by zero encountered in matmul
  w_tilda[t, :] = D_transposed @ w_tilda[t - 1, :]
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/tbats/abstract/ParamsOptimizer.py:150: RuntimeWarning: overflow encountered in matmul
  w_tilda[t, :] = D_transposed @ w_tilda[t - 1, :]
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/tbats/abstract/ParamsOptimizer.py:150: RuntimeWarning: invalid value encountered in matmul
  w_tilda[t, :] = D_transposed @ w_tilda[t - 1, :]
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/tbats/abstract/ParamsOptimizer.py:150: RuntimeWarning: divide by zero encountered in matmul
  w_tilda[t, :] = D_transposed @ w_tilda[t - 1, :]
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/tbats/abstract/ParamsOptimizer.py:150: RuntimeWarning: overflow encountered in matmul
  w_tilda[t, :] = D_transposed @ w_tilda[t - 1, :]
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/tbats/abstract/ParamsOptimizer.py:150: RuntimeWarning: invalid value encountered in matmul
  w_tilda[t, :] = D_transposed @ w_tilda[t - 1, :]
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/Users/jchan/miniconda3/envs/sales_forecasting/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [2]:
sales = pd.read_csv('pedidos-1743765883268.csv', sep=';', encoding='latin1')

In [3]:
df = sales[['account_id', 'sales_channel_id']].value_counts()
df = pd.DataFrame(df).reset_index()

In [4]:
SAO_PAULO_TZ = pytz.timezone('America/Sao_Paulo')
LOOKBACK = 1
SEASONAL_PERIODS = (24, 24*7)
# COVERAGE = 0.33
END_DATE = pd.to_datetime(pd.to_datetime(sales['created_date'].max()).strftime("%Y-%m-%d %H:00:00"))
# START_DATE = END_DATE - timedelta(hours=END_DATE.hour)
START_DATE = END_DATE - timedelta(hours=23)
TEST_SIZE = int((END_DATE - START_DATE).seconds / 60**2 + 1)

In [5]:
# OOT_DATE = START_DATE + timedelta(hours=23)

In [6]:
# OOT_PERIODS = int((OOT_DATE - END_DATE).seconds / 60**2 + 1)

In [7]:
# oot_dates = pd.DatetimeIndex([END_DATE+timedelta(hours=h) for h in range(1, OOT_PERIODS)], freq='h')
# df_oot = pd.DataFrame(index=oot_dates)

In [8]:
# df.drop('count', axis=1, inplace=True)
# for account_id in df['account_id'].unique():
#     df = pd.concat([df, pd.DataFrame({'account_id': [account_id], 'sales_channel_id': ['ALL']})], ignore_index=True)

In [9]:
df[df['account_id'] == '5f5ed10c-7792-4080-970c-b11398e3f58f']

                               account_id  sales_channel_id    count
0    5f5ed10c-7792-4080-970c-b11398e3f58f                 1  3004186
3    5f5ed10c-7792-4080-970c-b11398e3f58f                 9  1057418
6    5f5ed10c-7792-4080-970c-b11398e3f58f                 7   764881
10   5f5ed10c-7792-4080-970c-b11398e3f58f                 3   346390
13   5f5ed10c-7792-4080-970c-b11398e3f58f                20   297219
14   5f5ed10c-7792-4080-970c-b11398e3f58f                 8   271150
16   5f5ed10c-7792-4080-970c-b11398e3f58f                35   258514
23   5f5ed10c-7792-4080-970c-b11398e3f58f                 6   133119
25   5f5ed10c-7792-4080-970c-b11398e3f58f                 5   124741
26   5f5ed10c-7792-4080-970c-b11398e3f58f                 4   118931
30   5f5ed10c-7792-4080-970c-b11398e3f58f                13   103227
33   5f5ed10c-7792-4080-970c-b11398e3f58f                24    97118
39   5f5ed10c-7792-4080-970c-b11398e3f58f                16    78327
44   5f5ed10c-7792-4080-970c-b11398e3f58f                14    54139
47   5f5ed10c-7792-4080-970c-b11398e3f58f                15    49068
49   5f5ed10c-7792-4080-970c-b11398e3f58f                21    46722
61   5f5ed10c-7792-4080-970c-b11398e3f58f                 2    24532
68   5f5ed10c-7792-4080-970c-b11398e3f58f                12    17282
82   5f5ed10c-7792-4080-970c-b11398e3f58f                40    11949
85   5f5ed10c-7792-4080-970c-b11398e3f58f                39    11103
87   5f5ed10c-7792-4080-970c-b11398e3f58f                22     9713
91   5f5ed10c-7792-4080-970c-b11398e3f58f                32     9342
96   5f5ed10c-7792-4080-970c-b11398e3f58f                27     8592
98   5f5ed10c-7792-4080-970c-b11398e3f58f                23     8171
101  5f5ed10c-7792-4080-970c-b11398e3f58f                31     7359
112  5f5ed10c-7792-4080-970c-b11398e3f58f                25     5349
117  5f5ed10c-7792-4080-970c-b11398e3f58f                11     4057
122  5f5ed10c-7792-4080-970c-b11398e3f58f                17     3352
123  5f5ed10c-7792-4080-970c-b11398e3f58f                10     3323
128  5f5ed10c-7792-4080-970c-b11398e3f58f                36     2709
129  5f5ed10c-7792-4080-970c-b11398e3f58f                37     2647
138  5f5ed10c-7792-4080-970c-b11398e3f58f                41     2090
141  5f5ed10c-7792-4080-970c-b11398e3f58f                28     1929
170  5f5ed10c-7792-4080-970c-b11398e3f58f                34      992
176  5f5ed10c-7792-4080-970c-b11398e3f58f                19      738
189  5f5ed10c-7792-4080-970c-b11398e3f58f                18      425
190  5f5ed10c-7792-4080-970c-b11398e3f58f                30      425
219  5f5ed10c-7792-4080-970c-b11398e3f58f                29      158
220  5f5ed10c-7792-4080-970c-b11398e3f58f                26      154
258  5f5ed10c-7792-4080-970c-b11398e3f58f                42        9
271  5f5ed10c-7792-4080-970c-b11398e3f58f                38        3

In [10]:
account_ids = ['f9129295-bb08-4330-b60c-9f0beadda521', '05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6', '9d39683a-47b3-4a18-942d-f1d741a47e8c']

df_filtered = df[df['account_id'].isin(account_ids)]

In [11]:
df_filtered

                               account_id  sales_channel_id    count
1    9d39683a-47b3-4a18-942d-f1d741a47e8c                 1  2542841
2    05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6                 3  1908829
5    05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6                 6   876335
7    f9129295-bb08-4330-b60c-9f0beadda521                 1   486716
11   f9129295-bb08-4330-b60c-9f0beadda521                 2   321190
15   05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6                 5   263987
29   f9129295-bb08-4330-b60c-9f0beadda521                10   106300
48   f9129295-bb08-4330-b60c-9f0beadda521                38    47359
51   f9129295-bb08-4330-b60c-9f0beadda521                16    41229
55   f9129295-bb08-4330-b60c-9f0beadda521                18    29153
63   05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6                 1    20307
64   f9129295-bb08-4330-b60c-9f0beadda521                17    20111
86   f9129295-bb08-4330-b60c-9f0beadda521                 6    10374
88   f9129295-bb08-4330-b60c-9f0beadda521                22     9553
97   f9129295-bb08-4330-b60c-9f0beadda521                20     8467
105  f9129295-bb08-4330-b60c-9f0beadda521                31     6540
109  f9129295-bb08-4330-b60c-9f0beadda521                15     6072
110  f9129295-bb08-4330-b60c-9f0beadda521                43     5862
114  f9129295-bb08-4330-b60c-9f0beadda521                21     4857
116  f9129295-bb08-4330-b60c-9f0beadda521                39     4115
126  f9129295-bb08-4330-b60c-9f0beadda521                33     3209
137  f9129295-bb08-4330-b60c-9f0beadda521                32     2152
145  f9129295-bb08-4330-b60c-9f0beadda521                26     1769
146  f9129295-bb08-4330-b60c-9f0beadda521                19     1769
147  f9129295-bb08-4330-b60c-9f0beadda521                27     1757
148  f9129295-bb08-4330-b60c-9f0beadda521                 7     1654
156  f9129295-bb08-4330-b60c-9f0beadda521                34     1402
164  f9129295-bb08-4330-b60c-9f0beadda521                 3     1167
173  f9129295-bb08-4330-b60c-9f0beadda521                42      848
179  f9129295-bb08-4330-b60c-9f0beadda521                35      595
192  f9129295-bb08-4330-b60c-9f0beadda521                 4      388
195  f9129295-bb08-4330-b60c-9f0beadda521                11      352
197  f9129295-bb08-4330-b60c-9f0beadda521                24      339
207  f9129295-bb08-4330-b60c-9f0beadda521                13      211
208  f9129295-bb08-4330-b60c-9f0beadda521                29      207
233  f9129295-bb08-4330-b60c-9f0beadda521                25       60
235  9d39683a-47b3-4a18-942d-f1d741a47e8c                 2       40
243  05d9cc3a-decc-4fa2-b4e8-b44eef40e3b6                 4       24
245  f9129295-bb08-4330-b60c-9f0beadda521                 5       20
251  f9129295-bb08-4330-b60c-9f0beadda521                 8       14
273  f9129295-bb08-4330-b60c-9f0beadda521                36        1

In [12]:
dbname = 'railway'
username = 'sinatra'
pwd = '781B3XjpeuqE'
hostname = 'monorail.proxy.rlwy.net'
port = 25096

connection = psycopg2.connect(database=dbname, user=username, password=pwd, host=hostname, port=port)
cursor = connection.cursor()

In [13]:
# cursor.execute("select distinct account_id, channel from public.forecast where model='TBATS\_%';")

In [14]:
# res_forecast = cursor.fetchall()

In [15]:
id_pairs = list(zip(df_filtered['account_id'], df_filtered['sales_channel_id']))
# id_pairs = list(zip(df['account_id'], df['sales_channel_id']))
summary_dict = {}
forecast_dict = {}
for coverage in [n*10**-1 for n in range(1, 10)]:
    for account_id, sales_channel_id in id_pairs:
        account_id = 'f9129295-bb08-4330-b60c-9f0beadda521'
        sales_channel_id = 1
        # if (account_id, str(sales_channel_id)) in res_forecast:
        #     continue
        
        print(f'account_id: {account_id}')
        print(f'sales_channel_id: {sales_channel_id}')

        summary_dict[(account_id, sales_channel_id)] = {}
        
        if sales_channel_id == 'ALL':
            cond = (sales['account_id'] == account_id) & \
                   (sales['status'].notna())
        else:
            cond = (sales['account_id'] == account_id) & \
                   (sales['sales_channel_id'] == sales_channel_id) & \
                   (sales['status'].notna())

        df_client = sales[cond].drop(['account_id', 'sales_channel_id'], axis=1)
        df_client['created_date'] = pd.to_datetime(df_client['created_date'], format='%Y-%m-%d %H:%M:%S.%f %z')
        df_client = df_client.sort_values('created_date').reset_index(drop=True)
        df_client['created_date'] = df_client['created_date'].dt.strftime("%Y-%m-%d %H:00:00").reset_index(drop=True)

        df_client_mod = df_client.groupby('created_date').agg(price_total_agg=('price_total', 'sum'), n_orders=('created_date', 'count'))
        df_client_mod.index = pd.to_datetime(df_client_mod.index, format='%Y-%m-%d %H:00:00')

        end_date = pd.to_datetime(END_DATE, format='%Y-%m-%d %H:%M:%S')
        start_date = end_date - relativedelta(months=LOOKBACK)
        date_index = pd.Series(pd.date_range(start=start_date, end=end_date, freq='h', name='created_date'))
        df_client_mod = pd.merge(date_index, df_client_mod, how='left', on='created_date').set_index('created_date')

        # oot_date_index = pd.Series(df_oot.index, name='created_date')
        # combined_date_index = pd.concat([date_index, oot_date_index], axis=0)
        # df_client_mod = pd.merge(combined_date_index, df_client_mod, how='left', on='created_date').set_index('created_date')

        forecast_dict[account_id] = {} if account_id not in forecast_dict else forecast_dict[account_id]
        forecast_dict[account_id][sales_channel_id] = {}

        for n, col in enumerate(['price_total_agg', 'n_orders']):
            print(col)
            
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}'] = {}
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}']['name'] = col
            
            forecast_dict[account_id][sales_channel_id][f'dataset_{n}'] = {}
            
            df = df_client_mod[col]
            
            df.fillna(0, inplace=True)
            
            lags = [df.shift(l).rename(f'lag_{l}') for l in range(1, 25)]
            df_lag = pd.concat([df, pd.concat(lags, axis=1)], axis=1).dropna().asfreq('h')
            
            # df = df_lag.loc[df_lag.index <= END_DATE].copy()
            df_train = df_lag.loc[df_lag.index < START_DATE].copy()
            df_test = df_lag.loc[(df_lag.index >= START_DATE) & (df_lag.index <= END_DATE)].copy()
            # df_oot = df_lag.loc[df_lag.index > END_DATE].copy()

            # X, y = df.iloc[:, 1:], df.iloc[:, 0]
            X_train, y_train = df_train.iloc[:, 1:], df_train.iloc[:, 0]
            X_test, y_test = df_test.iloc[:, 1:], df_test.iloc[:, 0]
            # X_oot = df_oot.iloc[:, 1:]
            
            model = TBATS(sp=[24, 168], show_warnings=False, n_jobs=-1)
            model.fit(y_train)
            
            estimations = model.predict(fh=X_train.index)
            
            forecast = model.predict(fh=X_test.index)
            forecast_int = model.predict_interval(fh=X_test.index, coverage=coverage)
            forecast_lower = forecast_int.iloc[:, 0]
            forecast_upper = forecast_int.iloc[:, 1]
            
            forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['forecast'] = forecast
            forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['forecast_lower'] = forecast_lower
            forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['forecast_upper'] = forecast_upper
            
            # oot_model = TBATS(sp=[24, 168], show_warnings=False, n_jobs=-1)
            # oot_model.fit(y)
            
            # oot_forecast = oot_model.predict(fh=X_oot.index)
            # oot_forecast_int = oot_model.predict_interval(fh=X_oot.index, coverage=coverage)
            # oot_forecast_lower = oot_forecast_int.iloc[:, 0]
            # oot_forecast_upper = oot_forecast_int.iloc[:, 1]
            
            # forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['oot_forecast'] = oot_forecast
            # forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['oot_forecast_lower'] = oot_forecast_lower
            # forecast_dict[account_id][sales_channel_id][f'dataset_{n}']['oot_forecast_upper'] = oot_forecast_upper
            
            train_mae = mean_absolute_error(y_train, estimations)
            train_rmse = root_mean_squared_error(y_train, estimations)
            
            print(f"train RMSE: {train_rmse:.3f}")
            print(f"train MAE:  {train_mae:.3f}")
            
            test_mae = mean_absolute_error(y_test, forecast)
            test_rmse = root_mean_squared_error(y_test, forecast)

            print(f"test RMSE: {test_rmse:.3f}")
            print(f"test MAE:  {test_mae:.3f}")
            
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}']['train RMSE'] = train_rmse
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}']['test RMSE'] = test_rmse
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}']['train MAE'] = train_mae
            summary_dict[(account_id, sales_channel_id)][f'dataset_{n}']['test MAE'] = test_mae
            
            plt.figure(figsize=(12, 3))
            sns.lineplot(y_train.iloc[-3*TEST_SIZE:], lw=0.8, label='Train')
            sns.lineplot(estimations.iloc[-3*TEST_SIZE:], lw=0.8, label='Estimation')
            sns.lineplot(y_test, lw=0.8, label='Test', marker='o', markersize=3)
            sns.lineplot(forecast, lw=0.8, label='Forecast')
            sns.lineplot(forecast_lower, c='darkviolet', alpha=0.5, linestyle='--', lw=0.8)
            sns.lineplot(forecast_upper, c='darkviolet', alpha=0.5, linestyle='--', lw=0.8)
            sns.lineplot(2*forecast_lower-forecast, c='darkviolet', alpha=0.3, linestyle='--', lw=0.8)
            sns.lineplot(2*forecast_upper-forecast, c='darkviolet', alpha=0.3, linestyle='--', lw=0.8)
            # sns.lineplot(oot_forecast, lw=0.8, label='OOT Forecast')
            # sns.lineplot(oot_forecast_lower, c='darkviolet', linestyle='--', lw=0.8)
            # sns.lineplot(oot_forecast_upper, c='darkviolet', linestyle='--', lw=0.8)
            plt.fill_between(x=forecast.index,
                            y1=forecast_lower,
                            y2=forecast_upper,
                            color='violet',
                            alpha=0.5)
            plt.fill_between(x=forecast.index,
                            y1=2*forecast_lower-forecast,
                            y2=2*forecast_upper-forecast,
                            color='violet',
                            alpha=0.3)
            # plt.fill_between(x=oot_forecast.index,
            #                 y1=oot_forecast_lower,
            #                 y2=oot_forecast_upper,
            #                 color='violet',
            #                 alpha=0.5)
            plt.legend()
            plt.savefig(f'plots/time_series/forecast_{account_id}_{sales_channel_id}_{col}_ts.png')
            plt.show();

        # with open(f'sql/time_series/forecast_{account_id}_{sales_channel_id}_ts.sql', 'w') as output_file:
        #     pt_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_lower']
        #     pt_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_upper']
        #     pt_forecast = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast']
            
        #     no_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_lower']
        #     no_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_upper']
        #     no_forecast = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast']
        #     for i in range(len(df_test)):
        #         start_time = df_test.index[i]
        #         end_time = start_time + pd.Timedelta(hours=1)
        #         output_file.write(
        #             f"""
        #             INSERT INTO forecast (id, created, modified, platform, store_name, "start", "end",
        #                                   channel, seller, account_id, organization_id, store_id, minutes_interval,
        #                                   model, orders_high, orders_low, orders_mean, sales_high, sales_low, sales_mean)
        #             VALUES (gen_random_uuid(), now(), now(), 1, (select vtexid from vtex_account where id = '{account_id}'::uuid), '{start_time}', '{end_time}',
        #                     {sales_channel_id}, 'ALL', '{account_id}'::uuid, (select organizationid from vtex_account where id = '{account_id}'::uuid), NULL, 60, 'TBATS',
        #                     {no_forecast_upper.iloc[i]}, {no_forecast_lower.iloc[i]}, {no_forecast.iloc[i]},
        #                     {pt_forecast_upper.iloc[i]}, {pt_forecast_lower.iloc[i]}, {pt_forecast.iloc[i]});
        #             """
        #             )
            
        #     pt_oot_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast_lower']
        #     pt_oot_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast_upper']
        #     pt_oot_forecast = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast']
            
        #     no_oot_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast_lower']
        #     no_oot_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast_upper']
        #     no_oot_forecast = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast']
        #     for i in range(len(df_oot)):
        #         start_time = df_oot.index[i]
        #         end_time = start_time + pd.Timedelta(hours=1)
        #         output_file.write(
        #             f"""
        #             INSERT INTO forecast (id, created, modified, platform, store_name, "start", "end",
        #                                   channel, seller, account_id, organization_id, store_id, minutes_interval,
        #                                   model, orders_high, orders_low, orders_mean, sales_high, sales_low, sales_mean)
        #             VALUES (gen_random_uuid(), now(), now(), 1, (select vtexid from vtex_account where id = '{account_id}'::uuid), '{start_time}', '{end_time}',
        #                     {sales_channel_id}, 'ALL', '{account_id}'::uuid, (select organizationid from vtex_account where id = '{account_id}'::uuid), NULL, 60, 'TBATS',
        #                     {no_oot_forecast_upper.iloc[i]}, {no_oot_forecast_lower.iloc[i]}, {no_oot_forecast.iloc[i]},
        #                     {pt_oot_forecast_upper.iloc[i]}, {pt_oot_forecast_lower.iloc[i]}, {pt_oot_forecast.iloc[i]});
        #             """
        #         )
        
        # pt_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_lower']
        # pt_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_upper']
        # pt_forecast = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast']
        
        # no_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_lower']
        # no_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_upper']
        # no_forecast = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast']
        # for i in range(len(df_test)):
        #     start_time = df_test.index[i]
        #     end_time = start_time + pd.Timedelta(hours=1)
        #     start_time = start_time.tz_localize(SAO_PAULO_TZ)
        #     end_time = end_time.tz_localize(SAO_PAULO_TZ)
        #     insert = \
        #         f"""
        #         INSERT INTO public.forecast (id, created, modified, platform, store_name, "start", "end",
        #                                     channel, seller, account_id, organization_id, store_id, minutes_interval,
        #                                     model, orders_high, orders_low, orders_mean, sales_high, sales_low, sales_mean)
        #         VALUES (gen_random_uuid(), now(), now(), 1, '{account_id}'::uuid, '{start_time}', '{end_time}',
        #                 '{sales_channel_id}', 'ALL', '{account_id}'::uuid, '{account_id}'::uuid, NULL, 60, 'TBATS_{int(100*coverage)}',
        #                 {no_forecast_upper.iloc[i]}, {no_forecast_lower.iloc[i]}, {no_forecast.iloc[i]},
        #                 {pt_forecast_upper.iloc[i]}, {pt_forecast_lower.iloc[i]}, {pt_forecast.iloc[i]});
        #         """
        #     cursor.execute(insert)
        
        # pt_oot_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast_lower']
        # pt_oot_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast_upper']
        # pt_oot_forecast = forecast_dict[account_id][sales_channel_id]['dataset_0']['oot_forecast']
        
        # no_oot_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast_lower']
        # no_oot_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast_upper']
        # no_oot_forecast = forecast_dict[account_id][sales_channel_id]['dataset_1']['oot_forecast']
        # for i in range(len(df_oot)):
        #     start_time = df_oot.index[i]
        #     end_time = start_time + pd.Timedelta(hours=1)
        #     start_time = start_time.tz_localize(SAO_PAULO_TZ)
        #     end_time = end_time.tz_localize(SAO_PAULO_TZ)
        #     oot_insert = \
        #         f"""
        #         INSERT INTO public.forecast (id, created, modified, platform, store_name, "start", "end",
        #                                     channel, seller, account_id, organization_id, store_id, minutes_interval,
        #                                     model, orders_high, orders_low, orders_mean, sales_high, sales_low, sales_mean)
        #         VALUES (gen_random_uuid(), now(), now(), 1, '{account_id}'::uuid, '{start_time}', '{end_time}',
        #                 '{sales_channel_id}', 'ALL', '{account_id}'::uuid, '{account_id}'::uuid, NULL, 60, 'TBATS_{int(100*coverage)}',
        #                 {no_oot_forecast_upper.iloc[i]}, {no_oot_forecast_lower.iloc[i]}, {no_oot_forecast.iloc[i]},
        #                 {pt_oot_forecast_upper.iloc[i]}, {pt_oot_forecast_lower.iloc[i]}, {pt_oot_forecast.iloc[i]});
        #         """
        #     cursor.execute(oot_insert)
            
        cursor.execute('commit;')

account_id: f9129295-bb08-4330-b60c-9f0beadda521
sales_channel_id: 1
price_total_agg

ValueError: This LinearRegression estimator requires y to be passed, but the target y is None.

In [ ]:
# cursor.close()

In [ ]:
dataset_0 = pd.DataFrame({k: v['dataset_0'] for k, v in summary_dict.items()}).T
dataset_1 = pd.DataFrame({k: v['dataset_1'] for k, v in summary_dict.items()}).T

In [ ]:
summary = (
    pd
    .concat([dataset_0, dataset_1], axis=0)
    .rename({'name': 'dataset'}, axis=1)
    .sort_index()
    .reset_index(names=['account_id', 'sales_channel_id'])
)
summary.to_csv('summary_ts.csv', sep=';')

summary

# Evaluating Model

In [ ]:
for account_id, sales_channel_id in id_pairs:
    tbats_price_forecast = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast']
    tbats_price_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_lower']
    tbats_price_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_0']['forecast_upper']
    
    forecast_price_tbats = pd.concat([y_test, tbats_price_forecast, tbats_price_forecast_lower, tbats_price_forecast_upper], axis=1)
    forecast_price_tbats.columns = ['actual', 'forecast', 'lower', 'upper']
    
    df_forecast_price = forecast_price_tbats.assign(
        covered_pts=lambda x:
            4*x['actual'].between(x['lower'], x['upper'], inclusive='both') +
            2*(x['actual'].between(2*x['lower']-x['forecast'], x['lower'], inclusive='left') + x['actual'].between(x['upper'], 2*x['upper']-x['forecast'], inclusive='right')) +
            1*(x['actual'].between(3*x['lower']-2*x['forecast'], 2*x['lower']-x['forecast'], inclusive='left') + x['actual'].between(2*x['upper']-x['forecast'], 3*x['upper']-2*x['forecast'], inclusive='right')),
        covered_width=lambda x: x['upper'] - x['lower'],
    )
    
    df_forecast_price_metrics = df_forecast_price.agg(total_covered=('covered_pts', 'sum'), avg_covered=('covered_pts', 'mean'), avg_covered_width=('covered_width', 'mean'))
    
    df_forecast_price_metrics_norm = df_forecast_price_metrics['avg_covered']/(1 + np.log(1+df_forecast_price_metrics['avg_covered_width']))
    
    tbats_order_forecast = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast']
    tbats_order_forecast_lower = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_lower']
    tbats_order_forecast_upper = forecast_dict[account_id][sales_channel_id]['dataset_1']['forecast_upper']
    
    forecast_order_tbats = pd.concat([y_test, tbats_order_forecast, tbats_order_forecast_lower, tbats_order_forecast_upper], axis=1)
    forecast_order_tbats.columns = ['actual', 'forecast', 'lower', 'upper']
    
    df_forecast_order = forecast_order_tbats.assign(
        covered_pts=lambda x:
            4*x['actual'].between(x['lower'], x['upper'], inclusive='both') +
            2*(x['actual'].between(2*x['lower']-x['forecast'], x['lower'], inclusive='left') + x['actual'].between(x['upper'], 2*x['upper']-x['forecast'], inclusive='right')) +
            1*(x['actual'].between(3*x['lower']-2*x['forecast'], 2*x['lower']-x['forecast'], inclusive='left') + x['actual'].between(2*x['upper']-x['forecast'], 3*x['upper']-2*x['forecast'], inclusive='right')),
        covered_width=lambda x: x['upper'] - x['lower'],
    )
    
    df_forecast_order_metrics = df_forecast_order.agg(total_covered=('covered_pts', 'sum'), avg_covered=('covered_pts', 'mean'), avg_covered_width=('covered_width', 'mean'))
    
    df_forecast_order_metrics_norm = df_forecast_order_metrics['avg_covered']/(1 + np.log(1+df_forecast_order_metrics['avg_covered_width']))
    
    df_forecast_metrics_norm += 0.5*df_forecast_price_metrics_norm + 0.5*df_forecast_order_metrics_norm

In [ ]:
forecast_price_tbats = pd.concat([y_test, tbats_price_forecast, tbats_price_forecast_lower, tbats_price_forecast_upper], axis=1)
forecast_price_tbats.columns = ['actual', 'forecast', 'lower', 'upper']

In [ ]:
df_forecast_price = forecast_price_tbats.assign(
    covered_pts=lambda x:
        4*x['actual'].between(x['lower'], x['upper'], inclusive='both') +
        2*(x['actual'].between(2*x['lower']-x['forecast'], x['lower'], inclusive='left') + x['actual'].between(x['upper'], 2*x['upper']-x['forecast'], inclusive='right')) +
        1*(x['actual'].between(3*x['lower']-2*x['forecast'], 2*x['lower']-x['forecast'], inclusive='left') + x['actual'].between(2*x['upper']-x['forecast'], 3*x['upper']-2*x['forecast'], inclusive='right')),
    covered_width=lambda x: x['upper'] - x['lower'],
)

In [ ]:
df_forecast_price_metrics = df_forecast_price.agg(total_covered=('covered_pts', 'sum'), avg_covered=('covered_pts', 'mean'), avg_covered_width=('covered_width', 'mean'))

In [ ]:
df_forecast_price_metrics_norm = df_forecast_price_metrics['avg_covered']/np.log(1+df_forecast_price_metrics['avg_covered_width'])